export const actions = {
  NEW_PRICE: "NEW_PRICE",
  SELECT_CURRENCY: "SELECT_CURRENCY",
  FETCH_STOCK_QUOTE: "FETCH_STOCK_QUOTE",
  FETCH_STOCK_QUOTE_ERROR: "FETCH_STOCK_QUOTE_ERROR",
  RESET_CURRENCIES_STATE: "RESET_CURRENCIES_STATE",

  SELECT_EXCHANGE: "SELECT_EXCHANGE",
  FETCH_EXCHANGES: "FETCH_EXCHANGES",
  FETCH_EXCHANGES_ERROR: "FETCH_EXCHANGES_ERROR",

  SELECT_SYMBOL: "SELECT_SYMBOL",
  FETCH_SYMBOLS: "FETCH_SYMBOLS",
  FETCH_SYMBOLS_ERROR: "FETCH_SYMBOLS_ERROR",
  ADD_FAVORITE_SYMBOL: "ADD_FAVORITE_SYMBOL",
  REMOVE_FAVORITE_SYMBOL: "REMOVE_FAVORITE_SYMBOL",

  FETCH_CRYPTO_CANDLE: "FETCH_CRYPTO_CANDLE",
  FETCH_CRYPTO_CANDLE_ERROR: "FETCH_CRYPTO_CANDLE_ERROR",

  WEBSCOKET_LIVE_UPDATE: "WEBSCOKET_LIVE_UPDATE",
};
